//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.ExtensionKit.Tools.Converters.IPAddress {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IPAddressParser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IPAddressParser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.ExtensionKit.Tools.Converters.IPAddress.IPAddressParser", typeof(IPAddressParser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress Convertor.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress Convertor.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress Convertor.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Information.
        /// </summary>
        internal static string NetworkTitle {
            get {
                return ResourceManager.GetString("NetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string OutputTitle {
            get {
                return ResourceManager.GetString("OutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Subdivision.
        /// </summary>
        internal static string SubdivisionTitle {
            get {
                return ResourceManager.GetString("SubdivisionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subdivision Count.
        /// </summary>
        internal static string SubdivisionCountTitle {
            get {
                return ResourceManager.GetString("SubdivisionCountTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address: Input cannot be empty.
        /// </summary>
        internal static string ErrorEmptyInput {
            get {
                return ResourceManager.GetString("ErrorEmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address format: Must be in format xxx.xxx.xxx.xxx.
        /// </summary>
        internal static string ErrorInvalidIPFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidIPFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0} hosts.
        /// </summary>
        internal static string HostsCountFormat {
            get {
                return ResourceManager.GetString("HostsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Network: {0}.
        /// </summary>
        internal static string CurrentNetworkFormat {
            get {
                return ResourceManager.GetString("CurrentNetworkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If further subdivided:.
        /// </summary>
        internal static string IfFurtherSubdividedText {
            get {
                return ResourceManager.GetString("IfFurtherSubdividedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}: {1} subnets ({2:#,##0} hosts each).
        /// </summary>
        internal static string SubnetInfoFormat {
            get {
                return ResourceManager.GetString("SubnetInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddressTitle {
            get {
                return ResourceManager.GetString("IPAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix Length.
        /// </summary>
        internal static string PrefixLengthTitle {
            get {
                return ResourceManager.GetString("PrefixLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Address.
        /// </summary>
        internal static string NetworkAddressTitle {
            get {
                return ResourceManager.GetString("NetworkAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Mask.
        /// </summary>
        internal static string SubnetMaskTitle {
            get {
                return ResourceManager.GetString("SubnetMaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast Address.
        /// </summary>
        internal static string BroadcastAddressTitle {
            get {
                return ResourceManager.GetString("BroadcastAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard Mask.
        /// </summary>
        internal static string WildcardMaskTitle {
            get {
                return ResourceManager.GetString("WildcardMaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Host.
        /// </summary>
        internal static string FirstHostTitle {
            get {
                return ResourceManager.GetString("FirstHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Host.
        /// </summary>
        internal static string LastHostTitle {
            get {
                return ResourceManager.GetString("LastHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable Hosts.
        /// </summary>
        internal static string UsableHostsTitle {
            get {
                return ResourceManager.GetString("UsableHostsTitle", resourceCulture);
            }
        }
    }
}
