//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.ExtensionKit.Tools.EncodersDecoders.Unicode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnicodeEncoderDecoder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnicodeEncoderDecoder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.ExtensionKit.Tools.EncodersDecoders.Unicode.UnicodeEncoderDecoder", typeof(UnicodeEncoderDecoder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the CurrentUICulture property for all resource
        ///   lookups using this strongly-typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Encoder and Decoder tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code Point.
        /// </summary>
        internal static string CodePoint {
            get {
                return ResourceManager.GetString("CodePoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conversion error: {0}.
        /// </summary>
        internal static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string DecodeText {
            get {
                return ResourceManager.GetString("DecodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Encoder / Decoder.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Convert all characters to Unicode escape sequences, including ASCII characters..
        /// </summary>
        internal static string EncodeAllCharactersDescription {
            get {
                return ResourceManager.GetString("EncodeAllCharactersDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode All Characters (Encode mode only).
        /// </summary>
        internal static string EncodeAllCharactersTitle {
            get {
                return ResourceManager.GetString("EncodeAllCharactersTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Convert text to Unicode escape sequences..
        /// </summary>
        internal static string EncodeModeDescription {
            get {
                return ResourceManager.GetString("EncodeModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode Mode.
        /// </summary>
        internal static string EncodeModeTitle {
            get {
                return ResourceManager.GetString("EncodeModeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        internal static string EncodeText {
            get {
                return ResourceManager.GetString("EncodeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Encoder / Decoder.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Encoder / Decoder.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display Unicode information in a detailed table format..
        /// </summary>
        internal static string TableDisplayModeDescription {
            get {
                return ResourceManager.GetString("TableDisplayModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table Display Mode (Encode mode only).
        /// </summary>
        internal static string TableDisplayModeTitle {
            get {
                return ResourceManager.GetString("TableDisplayModeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unicode Information.
        /// </summary>
        internal static string UnicodeInformation {
            get {
                return ResourceManager.GetString("UnicodeInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UTF-16 (BE).
        /// </summary>
        internal static string UTF16BE {
            get {
                return ResourceManager.GetString("UTF16BE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        internal static string UTF8 {
            get {
                return ResourceManager.GetString("UTF8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
